### ISSUE TITLE
Driver API

### ISSUE THREAD

**Issue by scaryguy** [sishen/uber-ruby#25]
Do you consider adding the new API?

https://medium.com/uber-developers/uber-driver-api-b7191231e04d#.18p9hzolt

https://developer.uber.com/docs/drivers

**Comment by AnkurGel** [comment]
@scaryguy Should add it. Waiting for Uber to give me access to this API so that I can experiment and implement it. https://github.com/AnkurGel/uber-ruby/pull/1

**Comment by AnkurGel** [comment]
@chardane Hey! Can something be done regarding access? 😄

**Comment by chardane** [comment]
hey @AnkurGel ! I'm super bummed to say that I cannot give you access at this time since we're only giving out access to business partners right now. 😞 But, what I can do is I can help test it! 😄  You can build / mock with the [documentation for the three endpoints in the Driver API](https://developer.uber.com/docs/drivers) and I can help test to verify that it works. 

We are working on getting sandbox-only access to developers, so that people can easily build for new features like this. I'll definitely let you know when that happens!

**Comment by AnkurGel** [comment]
@chardane . Sure. It's ok :) Definitely let me know when sandbox mode access is available for this.

For implementation, I'm tracking it here - https://github.com/ankurgel/uber-ruby/pull/1, I still have to clean-up, write tests and documentation.Meanwhile, if you get time, do give it a try and check `client.partners.me`, `client.partners.payments`, `client.partners.trips`.

**Comment by chardane** [comment]
@AnkurGel hey can you DM me your client ID on twitter? I'm @chardane there as well. We can give you access so you can test this feature yourself! :)

**Comment by AnkurGel** [comment]
Thanks. I'm done with implementation - https://github.com/AnkurGel/uber-ruby/pull/1. 
@sishen @chardane  Please review it? :)

**Comment by chardane** [comment]
beautiful! will find some time to test this week! 🎉

**Comment by scaryguy** [comment]
Hey @AnkurGel , thanks for the fast implementation!

But I'm stuck at some point. Even without going to production, do I need to apply for access to this partners API?

Currently, when I try to -for example- access `client.partners.me`, I get `401` response.

When I check out my app at developer.uber.com, I can't select the check boxes because they are disabled. Do I need to apply for it by clicking 'Request Full Access' in order to be able to develop something using Partners API in even sandbox mode? But that form seems to be only about production product application. Isn't it?

Thank you very much for your help in advance.

**Comment by AnkurGel** [comment]
hi @scaryguy. 
AFAIK, Partners API is not available in sandbox mode. Yes, they are only available in production mode and you will have to request access for that :)
